# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Host Packages
          command: sudo apt-get install lxc -y

      - run:
          name: Environment
          command: node --version

      - run:
          name: Install Yarn
          command: sudo npm install -g yarn@~1.0.0

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Run Unit Tests
          command: export NODE_ENV=production && yarn run test

      - run:
          name: Run the Build
          command: yarn run build